### ISSUE TITLE
`bundle exec rubocop` が通りません

### ISSUE THREAD

**Issue by madapaja** [trainings-2015/team-b#2]
まず、`bundle exec rubocop` が通らない状況なので、それを改善してください。
通るようになった後にコードレビューします。

**Comment by jun-a** [comment]
こちら先ほど、実行してみました。
![2015-07-13 21 30 29](https://cloud.githubusercontent.com/assets/9759922/8649557/75648bf2-29a6-11e5-98fe-0d926e8ccc7d.png)
ローカルで実行した際には通りました。
rubocopを数回起動していますが、止まったことが無かったので、原因がわかりません。
申し訳ないです。

**Comment by madapaja** [comment]
通らない、というのは、動かない、ということではなく、全てがグリーン（問題ない）にならないという意味です。
グリーンの. （ドット）が表示されていない箇所は、rubocopが何らかの問題がある、と判断されたところなので、それらを解決してください。

**Comment by jun-a** [comment]
かしこまりました！修正します。
